services:
  proxyboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxyboard
    restart: unless-stopped
    network_mode: host
    environment:
      - UI_PORT=8088
      - XRAY_DOMAIN=vpn.itsnooblk.com
    volumes:
      - proxyboard-data:/data
    cap_add:
      - NET_BIND_SERVICE

volumes:
  proxyboard-data:
