services:
  xray-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xray-server
    restart: unless-stopped
    network_mode: host
    environment:
      - XRAY_LOGLEVEL=info
      - TZ=UTC
    stdin_open: true
    tty: true
    cap_add:
      - NET_BIND_SERVICE
